export default {
  hello: "HI  IAM MACIEJ SZYMAŃSKI",
  title: "A Front-end Developer & Programmer mentor",
  download: "Download CV",
  projectsPortfolio: "Projects",
  projects: "Projects",
  about: "About Me",
  contact: "Contact",
  moreProjects: "More Projects",
  followMe: "Follow Me",
  myDescription:
    "Hi, I’m Maciej Szymański and I’m a frontend developer with passion and ambition. For over two years, I’ve been commercially creating modern and useful web applications for government projects in Angular and Vue.js. I work in a scrum agile system and I know the best programming practices. I graduated from engineering studies in computer science and I plan to continue my education at master’s studies. I’m interested in chess, gym and new technologies and learning new things. My goal is to make history as one of the best programmers and innovators. I’m motivated by the fact that no one takes my words seriously and at the end of my life I want to show them all that they were wrong. I’m proud of my achievements, such as being the chairman of the computer science club for 4 years, where I help new and young ambitious students develop their skills, being the chairman of the student council for the whole year 2022 and completing the Frontend Bootcamp with React and a professional Vue.js 3 course at kodilla. I was also a mentor at one of the largest Polish bootcamps in Poland which is GoIT, where I help people take their first steps in HTML, CSS, Javascript and React.",
  experienceTitle: "Years of programming experience",
  commercialExperienceTitle: "Years of commercial programming experience",
  feedbackTitle: "satisfied customers",
  projectsTitle: "Completed projects",
  clientsHeading: "Some of the brands I have worked with",
  skills: "Skills",
  contactDetails: "Contact Details",
  contactForm: "Contact Form",
  fullName: "Full Name",
  email: "Email",
  message: "Message",
  send: "Send Message",
};
