export default {
  hello: "CZEŚĆ, JESTEM MACIEJ SZYMAŃSKI",
  title: "Front-end Developer i Mentor Programistyczny",
  download: "Pobierz CV",
  projectsPortfolio: "Projekty",
  projects: "Projekty",
  about: "O mnie",
  contact: "Kontakt",
  moreProjects: "Więcej projektów",
  followMe: "Znajdź mnie na",
  myDescription:
    "Cześć, jestem Maciej Szymański i jestem frontend developerem z pasją i ambicją. Od ponad dwóch lat komercyjnie tworzę nowoczesne i użyteczne aplikacje internetowe dla projektów rządowych w Angularze i Vue.js. Pracuję w systemie scrum agile i znam się na najlepszych praktykach programistycznych. Ukończyłem studia inżynierskie z informatyki i planuję kontynuować edukację na studiach magisterskich. Interesuję się szachami, siłownią i nowymi technologiami oraz zdobywaniem nowej wiedzy. Moim celem jest zapisać się w historii ludzkości jako jeden z lepszych programistów i pomysłodawców. Motywuje mnie to, że nikt nie bierze moich słów na poważnie i pod koniec życia chcę pokazać im wszystkim że się mylili. Jestem dumny z moich osiągnięć, takich jak bycie od 4 lat przewodniczącym koła informatyki, gdzie pomagam w rozwoju nowym i młodym ambitnym studentom, bycie przewodniczącym samorządu studentów przez cały rok 2022 oraz ukończenie Bootcampu Frontendowego z Reacta oraz profesjonalnego kursu Vue.js 3 na kodilli. Byłem również mentorem w jednym z największych polskich bootcampów w polsce jakim jest GoIT, gdzie pomgadam ludziom stawiać swoje pierwsze kroki w HTML, CSS, Javascript i reacie.",
  experienceTitle: "Lata doświadczenia w programowaniu",
  commercialExperienceTitle: "Lata doświadczenia komercyjnego",
  feedbackTitle: "zadowolonych klientów",
  projectsTitle: "Ukonczone projekty",
  clientsHeading: "Współpracowałem z takimi firmami jak",
  skills: "Umiejętności",
  contactDetails: "Dane kontaktowe",
  contactForm: "Formularz kontaktowy",
  fullName: "Imię i nazwisko",
  email: "Email",
  message: "Wiadomość",
  send: "Wyślij wiadomość",
};
